### ISSUE TITLE
Using ExpandableListItem with Android transition causes fragments of expanded views to remain

### ISSUE THREAD

**Issue by DreaminginCodeZH** [nhaarman/ListViewAnimations#290]
Platform version: 4.4.2

Library version: Latest in Maven

Steps to reproduce:

1. Implement an ExpandableListItem list, and use 4.4 TransitionManager to start a transition when the content of list needs to be changed, as follow:

    ```java
    // When data is loaded.
    TransitionManager.beginDelayedTransition(viewGroup, new CrossFade(context));

    // The crossfade class.
    @TargetApi(Build.VERSION_CODES.KITKAT)
    private static class CrossFade extends TransitionSet {

        public CrossFade(Context context) {
            setOrdering(ORDERING_TOGETHER);
            int duration = context.getResources().getInteger(
                    android.R.integer.config_shortAnimTime);
            setDuration(duration);
            addTransition(new Fade(Fade.OUT));
            addTransition(new Fade(Fade.IN));
        }
    }
    ```

    Note that in order to get Transition to work, I made hasStableIds() return true in the adapter.

2. Expand multiple views, then change the list's data.

3. The crossfade starts, but some views of the expanded items remain on screen.

A screenshot of the issue (my app is in Chinese), the remaining views are all in the expanded part of the list item:

![Fragments of previous views](https://cloud.githubusercontent.com/assets/4469895/4912947/28d78ae2-64a7-11e4-8853-84602a9de3e6.png)

**Comment by nhaarman** [comment]
This seems to be LVA-unrelated.
