### ISSUE TITLE
swipe to dismiss removes text from random list items

### ISSUE THREAD

**Issue by Sahasrara** [nhaarman/ListViewAnimations#297]
I'm using a DynamicListView with an ArrayAdapter that implements Swappable.

The list is setup with the following:

```java
list.enableDragAndDrop();
list.setOnItemLongClickListener(new OnItemLongClickListener() {...} // used for swapping
list.enableSwipeToDismiss(new OnDismissCallback() {...});
list.setOnItemClickListener(new AdapterView.OnItemClickListener() {...}
```

When I swipe away an item, sometimes random rows will lose their text.  The rows have two TextViews, an ImageView, and a ProgressBar.  Only one of the TextViews will ever lose its text on any given row after a swipe to dismiss.

The onDismiss callback looks like this:

```java
public void onDismiss(final ViewGroup listView, final int[] reverseSortedPositions) {
    for (int position : reverseSortedPositions) {
        queue.remove(position);
        adapter.notifyDatasetChanged();
    }
}
```

**Comment by robertdo** [comment]
@Sahasrara Could you elaborate more on your workaround?

**Comment by Sahasrara** [comment]
Hey there, I'm sorry to say it's been so long since I last worked on android that I forgot what the issue was exactly.  I did eventually solve whatever issue I was having without a workaround and I can point you to the project I was working on.  The class in question is QueueAdapter.

https://github.com/Sahasrara/Subtle/blob/master/Subtle/src/com/example/subtle/QueueAdapter.java
