### ISSUE TITLE
How to perform an animation on each Activity.onResume()?

### ISSUE THREAD

**Issue by kamoljan** [nhaarman/ListViewAnimations#310]
Hi @nhaarman 

Thank you very much for your library!

    However, something is bothering me, how to perform an animation on each Activity.onResume()?

Sometimes it animates and sometimes it doesn't.

Here `INITIAL_DELAY_MILLIS`:

    private static final int INITIAL_DELAY_MILLIS = 300;

Here the peace of code which runs on Activity.onResume():

    MainAdapter categoryAdapter = new MainAdapter(this);
    AlphaInAnimationAdapter animationAdapter = new AlphaInAnimationAdapter(categoryAdapter);
    animationAdapter.setAbsListView(lvCategory);
    assert animationAdapter.getViewAnimator() != null;
    animationAdapter.getViewAnimator().setInitialDelayMillis(INITIAL_DELAY_MILLIS);
    lvCategory.setAdapter(animationAdapter);
    categoryAdapter.loadObjects();

**Comment by nhaarman** [comment]
Use the `reset()` method on the `AnimatinoAdapter`.
