### ISSUE TITLE
DynamicListView Drag and Drop custom adapter

### ISSUE THREAD

**Issue by kenny0202** [nhaarman/ListViewAnimations#312]
Hey nhaarman, 
I would like to thank you for this awesome library.

I have added some sample data into an arraylist for testing purposes. and have ran into a problem where the error states 
" Adapter doesn't have stable ids! Make sure your adapter has stable ids, and override hasStableIds() to return true." 

I was thinking about to create a custom array adapter myself 

here is how part of my code looks like as im getting an error on "lv.enableDragAndDrop();"

this listview is displayed in a fragment

    lv = (DynamicListView) v.findViewById(R.id.dynamic_listview);
    
        final ArrayAdapter<String> adapter = new ArrayAdapter<String>(getActivity(), android.R.layout.simple_list_item_1, list);
        lv.setAdapter(adapter);
        adapter.notifyDataSetChanged();
        lv.enableDragAndDrop();
        lv.setOnItemLongClickListener(new AdapterView.OnItemLongClickListener() {
            @Override
            public boolean onItemLongClick(final AdapterView<?> parent, final View view,
                                           final int position, final long id) {
                lv.startDragging(position);
                return true;
            }
        });

**Comment by charlag** [comment]
I would suggest you to write custom adapter that inherits from BaseAdapter. In it you should override 
    hasStableIds() to return true. For stable id's you could do something like
public long getItemId(int) { return getItem(i).hashCode(); }
Also your adapter has to implement swapItems().
Good luck.

**Comment by nhaarman** [comment]
Solution as provided above.
