### ISSUE TITLE
in eclipse i have added jar file in libs folder but stilll getting this error ....Pls guide

### ISSUE THREAD

**Issue by erumhannan** [nhaarman/ListViewAnimations#318]
12-22 12:41:35.735: E/dalvikvm(1784): Could not find class 'com.haarman.listviewanimations.swinginadapters.prepared.SwingBottomInAnimationAdapter', referenced from method com.mygallery.HomeActivity.updateListView

**Comment by erumhannan** [comment]
have anyone resolved this issue ?

**Comment by curtis2** [comment]
Just no, thanks.

在 2015-01-10 01:05:26，"erumhannan" <notifications@github.com> 写道：


have anyone resolved this issue ?

**Comment by nhaarman** [comment]
Android Studio is the recommended IDE now.
