### ISSUE TITLE
Please help to verify three libraries compatible with Android support v7 library: 21.0.3 for Android L 

### ISSUE THREAD

**Issue by leanwang** [nhaarman/ListViewAnimations#320]
I build an App using Android Studio 1.0.1 with v7 librariy, 21.0.3.   During run time, logcat shows many warnings:

01-03 14:16:30.933  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve virtual method 11371: Landroid/view/ViewGroup;.onNestedScrollAccepted (Landroid/view/View;Landroid/view/View;I)V
01-03 14:16:30.933  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve virtual method 11377: Landroid/view/ViewGroup;.onStopNestedScroll (Landroid/view/View;)V
01-03 14:16:30.933  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve virtual method 11379: Landroid/view/ViewGroup;.onWindowSystemUiVisibilityChanged (I)V
01-03 14:16:30.933  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve virtual method 9047: Landroid/support/v7/internal/widget/ActionBarOverlayLayout;.stopNestedScroll ()V
01-03 14:16:30.963  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve virtual method 11374: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
01-03 14:16:30.973  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve virtual method 369: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
01-03 14:16:30.973  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve virtual method 391: Landroid/content/res/TypedArray;.getType (I)I
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist D/+++++  GoogleCardsAdapter? GoogleCardsAdapter() enter!!  a new Object GoogleCardsAdapter is created!!
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist D/+++++  BitmapCache? BitmapCache() enters!  a new Object BitmapCache  is created!!
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve static method 12634: Lcom/nineoldandroids/animation/ObjectAnimator;.ofFloat (Ljava/lang/Object;Ljava/lang/String;[F)Lcom/nineoldandroids/animation/ObjectAnimator;
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to find class referenced in signature (Lcom/nineoldandroids/animation/Animator;)
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist E/dalvikvm? Could not find class 'com.nineoldandroids.animation.Animator[]', referenced from method com.nhaarman.listviewanimations.appearance.SingleAnimationAdapter.getAnimators
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve new-array 1733 ([Lcom/nineoldandroids/animation/Animator;) in Lcom/nhaarman/listviewanimations/appearance/SingleAnimationAdapter;
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to find class referenced in signature ([Lcom/nineoldandroids/animation/Animator;)
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to find class referenced in signature ([Lcom/nineoldandroids/animation/Animator;)
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve static method 12634: Lcom/nineoldandroids/animation/ObjectAnimator;.ofFloat (Ljava/lang/Object;Ljava/lang/String;[F)Lcom/nineoldandroids/animation/ObjectAnimator;
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist E/dalvikvm? Could not find class 'com.nineoldandroids.animation.Animator[]', referenced from method com.nhaarman.listviewanimations.appearance.AnimationAdapter.animateViewIfNecessary
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve new-array 1733 ([Lcom/nineoldandroids/animation/Animator;) in Lcom/nhaarman/listviewanimations/appearance/AnimationAdapter;
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve static method 12639: Lcom/nineoldandroids/animation/ValueAnimator;.ofInt ([I)Lcom/nineoldandroids/animation/ValueAnimator;
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? Link of class 'Lcom/nhaarman/listviewanimations/itemmanipulation/swipedismiss/SwipeDismissTouchListener$DismissAnimatorUpdateListener;' failed
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? Unable to resolve superclass of Lcom/nhaarman/listviewanimations/itemmanipulation/swipedismiss/SwipeDismissTouchListener$DismissAnimatorListener; (1564)
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? Link of class 'Lcom/nhaarman/listviewanimations/itemmanipulation/swipedismiss/SwipeDismissTouchListener$DismissAnimatorListener;' failed
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve static method 12634: Lcom/nineoldandroids/animation/ObjectAnimator;.ofFloat (Ljava/lang/Object;Ljava/lang/String;[F)Lcom/nineoldandroids/animation/ObjectAnimator;
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve static method 12643: Lcom/nineoldandroids/view/ViewHelper;.setTranslationX (Landroid/view/View;F)V
01-03 14:16:31.013  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve static method 12643: Lcom/nineoldandroids/view/ViewHelper;.setTranslationX (Landroid/view/View;F)V
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve static method 12634: Lcom/nineoldandroids/animation/ObjectAnimator;.ofFloat (Ljava/lang/Object;Ljava/lang/String;[F)Lcom/nineoldandroids/animation/ObjectAnimator;
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve static method 12642: Lcom/nineoldandroids/view/ViewHelper;.setAlpha (Landroid/view/View;F)V
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? Unable to resolve superclass of Lcom/nhaarman/listviewanimations/itemmanipulation/swipedismiss/SwipeTouchListener$FlingAnimatorListener; (1564)
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? Link of class 'Lcom/nhaarman/listviewanimations/itemmanipulation/swipedismiss/SwipeTouchListener$FlingAnimatorListener;' failed
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? Unable to resolve superclass of Lcom/nhaarman/listviewanimations/itemmanipulation/swipedismiss/SwipeTouchListener$RestoreAnimatorListener; (1564)
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? Link of class 'Lcom/nhaarman/listviewanimations/itemmanipulation/swipedismiss/SwipeTouchListener$RestoreAnimatorListener;' failed
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to find class referenced in signature ([Lcom/nineoldandroids/animation/Animator;)
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve static method 12642: Lcom/nineoldandroids/view/ViewHelper;.setAlpha (Landroid/view/View;F)V
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to find class referenced in signature ([Lcom/nineoldandroids/animation/Animator;)
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to find class referenced in signature ([Lcom/nineoldandroids/animation/Animator;)
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist E/dalvikvm? Could not find class 'com.nineoldandroids.animation.Animator', referenced from method com.nhaarman.listviewanimations.appearance.ViewAnimator.cancelExistingAnimation
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve check-cast 1562 (Lcom/nineoldandroids/animation/Animator;) in Lcom/nhaarman/listviewanimations/appearance/ViewAnimator;
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist E/dalvikvm? Could not find class 'com.nineoldandroids.animation.Animator', referenced from method com.nhaarman.listviewanimations.appearance.ViewAnimator.reset
01-03 14:16:31.023  26622-26622/com.leanwang.destinationlist W/dalvikvm? VFY: unable to resolve check-cast 1562 (Lcom/nineoldandroids/animation/Animator;) in Lcom/nhaarman/listviewanimations/appearance/ViewAnimator;

it seems your libraries are built to support support library: 20.0.0.  Knowing the support library built for Android L has substantial differences to 20.0.0 to support new features in Android L, wonder these warnings and the Exception that I get from executing my app is because by this.

01-03 14:16:31.234  26622-26622/com.leanwang.destinationlist W/dalvikvm? threadid=1: thread exiting with uncaught exception (group=0x40bf11f8)
01-03 14:16:31.234  26622-26622/com.leanwang.destinationlist E/AndroidRuntime? FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.nineoldandroids.animation.Animator[]
            at com.nhaarman.listviewanimations.appearance.AnimationAdapter.animateViewIfNecessary(AnimationAdapter.java:174)
            at com.nhaarman.listviewanimations.appearance.AnimationAdapter.getView(AnimationAdapter.java:145)
            at android.widget.AbsListView.obtainView(AbsListView.java:2222)
            at android.widget.ListView.makeAndAddView(ListView.java:1774)
            at android.widget.ListView.fillDown(ListView.java:672)
            at android.widget.ListView.fillFromTop(ListView.java:732)
            at android.widget.ListView.layoutChildren(ListView.java:1611)
            at android.widget.AbsListView.onLayout(AbsListView.java:2052)
            at android.view.View.layout(View.java:11460)
            at android.view.ViewGroup.layout(ViewGroup.java:4229)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1644)
            at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1633)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1417)
            at android.view.View.layout(View.java:11460)
            at android.view.ViewGroup.layout(ViewGroup.java:4229)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
            at android.view.View.layout(View.java:11460)
            at android.view.ViewGroup.layout(ViewGroup.java:4229)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
            at android.view.View.layout(View.java:11460)
            at android.view.ViewGroup.layout(ViewGroup.java:4229)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
            at android.view.View.layout(View.java:11460)
            at android.view.ViewGroup.layout(ViewGroup.java:4229)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1644)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1502)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
            at android.view.View.layout(View.java:11460)
            at android.view.ViewGroup.layout(ViewGroup.java:4229)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
            at android.view.View.layout(View.java:11460)
            at android.view.ViewGroup.layout(ViewGroup.java:4229)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1671)
            at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2628)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4511)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:976)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:743)
            at dalvik.system.NativeStart.main(Native Method)
 
Many thanks!

Lean Wang

**Comment by DreaminginCodeZH** [comment]
Please integrate nineoldandroids into your project.

**Comment by leanwang** [comment]
You are right!  This fixes my problem!  Million thanks!
