### ISSUE TITLE
Handling end of longlick

### ISSUE THREAD

**Issue by charlag** [nhaarman/ListViewAnimations#321]
I am trying to use SwipeRefreshLayout with DynamicListView in one activity. The problem is when I am trying to drag view down, I can not because swipe-to-refresh is pulling down. Now I use workaround: in onItemLongClick() I disable the SwipeRefreshLayout. But I can't handle MotionEvent.ACTION_UP. I think dragging handler does the work and does not notify others. Is there any solution?

**Comment by nhaarman** [comment]
Use `OnItemMovedListener`.
