### ISSUE TITLE
Using custom adapter dynamic listview giving me a null pointer exception

### ISSUE THREAD

**Issue by dubrechi** [nhaarman/ListViewAnimations#323]
Hi nhaarman

First of all, thank you for this wonderful library! im a noob in programming and im trying to figure out what's wrong with my implementation, im trying to use the dyamiclistview but when everytime i try to drag and move the component, my application stop, 

i hope you can help me, thanks in advance.

here is my code: 

package com.example.dynamiclistviewusingbaseadapter;

import com.nhaarman.listviewanimations.appearance.simple.AlphaInAnimationAdapter;
import com.nhaarman.listviewanimations.itemmanipulation.DynamicListView;
import com.nhaarman.listviewanimations.itemmanipulation.dragdrop.TouchViewDraggableManager;
import com.nhaarman.listviewanimations.util.Swappable;

import android.support.annotation.NonNull;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemLongClickListener;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.TextView;

public class MainActivity extends ActionBarActivity {

	   DynamicListView l1;
	    String[] t1={"video1","video2"};
	    String[] d1={"lesson1","lesson2"};
	    int[] i1 ={R.drawable.ic_launcher,R.drawable.ic_launcher};

	    @Override
	    protected void onCreate(Bundle savedInstanceState) {
	        super.onCreate(savedInstanceState);
	        setContentView(R.layout.activity_main);
	        l1=(DynamicListView)findViewById(R.id.dynamiclistview);
	        
	        AlphaInAnimationAdapter animatorAdapter = new AlphaInAnimationAdapter(new dataListAdapter(t1,d1,i1));
	        animatorAdapter.setAbsListView(l1);
	        l1.setAdapter(animatorAdapter);
	        l1.enableDragAndDrop();
	        l1.setDraggableManager(new TouchViewDraggableManager(R.layout.custom));
	        l1.setOnItemLongClickListener(new OnItemLongClickListener() {

				@Override
				public boolean onItemLongClick(AdapterView<?> parent,
						View view, int position, long id) {
		            if (l1 != null) {
		            	l1.startDragging(position - l1.getHeaderViewsCount());
		            }
		            return true;
//					l1.startDragging(position);
//					return true;
				}
			});
	        
	    }

	    class dataListAdapter extends BaseAdapter implements Swappable {
	        String[] Title, Detail;
	        int[] imge;

	        dataListAdapter() {
	            Title = null;
	            Detail = null;
	            imge=null;
	        }

	        public dataListAdapter(String[] text, String[] text1,int[] text3) {
	            Title = text;
	            Detail = text1;
	            imge = text3;

	        }

	        public int getCount() {
	            return Title.length;
	        }

	        public Object getItem(int arg0) {
	            return null;
	        }
	        
	        @Override
	        public boolean hasStableIds() {
	        	return true;
	        }

	        public long getItemId(int position) {
	            return position;
	        }

	        public View getView(int position, View convertView, ViewGroup parent) {

	            LayoutInflater inflater = getLayoutInflater();
	            View row;
	            row = inflater.inflate(R.layout.custom, parent, false);
	            TextView title, detail;
	            ImageView i1;
	            title = (TextView) row.findViewById(R.id.title);
	            detail = (TextView) row.findViewById(R.id.detail);
	            i1=(ImageView)row.findViewById(R.id.img);
	            title.setText(Title[position]);
	            detail.setText(Detail[position]);
	            i1.setImageResource(imge[position]);

	            return (row);
	        }

			@Override
			public void swapItems(int arg0, int arg1) {
				// TODO Auto-generated method stub
				
			}
	    }
}

**Comment by nbau21** [comment]
What line specifically causes the Null Pointer Exception?

**Comment by nhaarman** [comment]
Closing due to a lack of information.
