### ISSUE TITLE
Push below views on item expand

### ISSUE THREAD

**Issue by MohamadAtieh** [nhaarman/ListViewAnimations#329]
I have a problem. The listview that contains the items should match the parent. However, when there is a static view below this ListView, the item content blinks full height before starting animation.

I'm trying to do this http://stackoverflow.com/questions/4946295/android-expand-collapse-animation

Which method should I override? And what should I watch for? I can't call **super** since the animation will be triggered and it is what I'm trying to do basically.

**Comment by nhaarman** [comment]
This seems unrelated to LVA.
