### ISSUE TITLE
Is this library still under development?

### ISSUE THREAD

**Issue by MrBrightside29** [nhaarman/ListViewAnimations#331]
It has been a while since the last update and there are many questions/ issues without reply, so I'm thinking to give a try to other similar libraries which have some improvements.

**Comment by ChrisMCMine** [comment]
Have you found any libraries with the same feature set?

**Comment by MrBrightside29** [comment]
Well.. I've found one which has nice features but needs to be used with the new RecyclerView and in my case implies a lot of work to change the code. https://android-arsenal.com/details/1/1432
