### ISSUE TITLE
ListViewAnimations Setup inside of Android Studio

### ISSUE THREAD

**Issue by a1exus** [nhaarman/ListViewAnimations#334]
I'm trying to setup "nhaarman/ListViewAnimations" inside of Android Studio 1.1.0.

From [Setup](https://github.com/nhaarman/ListViewAnimations#setup):

Add the following to your build.gradle:
```
repositories {
    mavenCentral()
}

dependencies {
    compile 'com.nhaarman.listviewanimations:lib-core:3.1.0@aar'
    compile 'com.nhaarman.listviewanimations:lib-manipulation:3.1.0@aar'
    compile 'com.nhaarman.listviewanimations:lib-core-slh:3.1.0@aar'
}
```
yet Android Studio says:

Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly. 

```
Error:(26, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'X' may be using a version of Gradle that does not contain the method.
<a href="openGradleSettings">Gradle settings</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>
```

**Comment by MGaetan89** [comment]
This looks more like an issue in your project than in this library.

**Comment by a1exus** [comment]
It could very well be. I created brand new project and added those lines to build.gradle.

I'm using Android Studio 1.1 with Gradle 2.2.1

**Comment by a1exus** [comment]
after adding those lines to:

```build.gradle (Module: app)```

instead of

```build.gradle (Project: app)```

no errors)
