### ISSUE TITLE
On swipe callback

### ISSUE THREAD

**Issue by martinbaciga** [nhaarman/ListViewAnimations#335]
Hi!, i would like to know if i can get some kind of callback that tells me that the user has swiped an item of the listview. It this posible? Thanks!

**Comment by MrBrightside29** [comment]
Yes, of course you can. You have the onDIsmiss callback when you enable swipe to dismiss.
    
listView.enableSwipeToDismiss(
                new OnDismissCallback() {
                    @Override
                    public void onDismiss(@NonNull final ViewGroup list, @NonNull final int[] reverseSortedPositions) {
                        for (final int position : reverseSortedPositions) {
....

**Comment by hazico** [comment]
Hi,
Is there another callback that can indicate the swipe direction?
I'm trying to create different behaviour for swipe right and swipe left

**Comment by MrBrightside29** [comment]
Nop. :(
