### ISSUE TITLE
Swipe To Dismiss prevent some items to swipe.

### ISSUE THREAD

**Issue by anzaidemirzoi** [nhaarman/ListViewAnimations#348]
Hi, 

is it possible to prevent some items to swipe ?

**Comment by igozhenko** [comment]
I want to know, too

**Comment by igozhenko** [comment]
@anzaidemirzoi Found it.

See [DismissableManager](https://github.com/nhaarman/ListViewAnimations/blob/master/lib-manipulation/src/main/java/com/nhaarman/listviewanimations/itemmanipulation/swipedismiss/DismissableManager.java). Usage [DynamicListView.setDismissableManager](https://github.com/nhaarman/ListViewAnimations/blob/4aa6dd2253c6132b121497cd3e729962f411d0d3/lib-manipulation/src/main/java/com/nhaarman/listviewanimations/itemmanipulation/DynamicListView.java#L456)

**Comment by anzaidemirzoi** [comment]
it works thank you :)
